version: '3.1'
services:
  my-spring-boot:
    build: .
    restart: always
    ports:
      - 5000:5000
    environment:
      SERVER_PORT: 5000
      APP_PLANET: mars
      SPRING_DATA_MONGODB_HOST: mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 2701:2701
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
  mongodb:
  mongodb_config:
